// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5k3oRV6ckLvIvsJAoQSQbLm_r_0HUakY',
    appId: '1:935408326505:web:e10491324a571fb6480ff8',
    messagingSenderId: '935408326505',
    projectId: 'libravault-1b064',
    authDomain: 'libravault-1b064.firebaseapp.com',
    storageBucket: 'libravault-1b064.firebasestorage.app',
    measurementId: 'G-69L7F4K8N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ0nMB0zu4HRk5Y82DcErno3wNQ-3LDtQ',
    appId: '1:935408326505:android:55c3da44db47038e480ff8',
    messagingSenderId: '935408326505',
    projectId: 'libravault-1b064',
    storageBucket: 'libravault-1b064.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7sSJu8qwYOzsv4-Hdbg-eBBKBL0SN5dU',
    appId: '1:935408326505:ios:d8a25af3f048b83d480ff8',
    messagingSenderId: '935408326505',
    projectId: 'libravault-1b064',
    storageBucket: 'libravault-1b064.firebasestorage.app',
    iosBundleId: 'com.example.libraryMan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7sSJu8qwYOzsv4-Hdbg-eBBKBL0SN5dU',
    appId: '1:935408326505:ios:d8a25af3f048b83d480ff8',
    messagingSenderId: '935408326505',
    projectId: 'libravault-1b064',
    storageBucket: 'libravault-1b064.firebasestorage.app',
    iosBundleId: 'com.example.libraryMan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5k3oRV6ckLvIvsJAoQSQbLm_r_0HUakY',
    appId: '1:935408326505:web:039a6892c00602d9480ff8',
    messagingSenderId: '935408326505',
    projectId: 'libravault-1b064',
    authDomain: 'libravault-1b064.firebaseapp.com',
    storageBucket: 'libravault-1b064.firebasestorage.app',
    measurementId: 'G-W5YJN3WQDC',
  );
}
